server:
  port: 18080
spring:
  application:
    name: zuul-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8722
zuul:
  routes:
    fegin-route:
      path: /fegin/**
      serviceId: fegin-service
      strip-prefix: false
