server:
  port: 8852
spring:
  application:
    name: dubbo-provider-service
  cloud:
    #Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口。
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    #在 Spring Boot 2.1 以及更高的版本增加该设定，因为 Spring Boot 默认调整了 Bean 定义覆盖行为。
    allow-bean-definition-overriding: true
dubbo:
  registry:
    #Dubbo 服务注册中心配置，其中子属性address 的值 "spring-cloud://localhost"，说明挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  protocol:
    #Dubbo服务暴露的协议配置，属性name为协议名称
    name: dubbo
    #port为协议端口（-1 表示自增端口，从 20880 开始）
    port: -1
  scan:
    #指定 Dubbo 服务实现类的扫描基准包
    base-packages: com.exception