server:
  port: 8854
spring:
  application:
    name: sentinel-service
  cloud:
    sentinel:
      transport:
        #配置Sentinel控制台的ip和端口
        dashboard: 127.0.0.1:8080
        #这个端口配置会在应用对应的机器上启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互。
        #比如 Sentinel 控制台添加了1个限流规则，会把规则数据 push 给这个 Http Server 接收，Http Server 再将规则注册到 Sentinel 中。
        port: 8719